"""empty message

Revision ID: 0048aee1d847
Revises: 
Create Date: 2024-03-19 14:27:32.525200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0048aee1d847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('event_num', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_table'))
    )
    op.create_table('fighter_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fighter_table'))
    )
    op.create_table('match_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_1_name', sa.String(), nullable=False),
    sa.Column('fighter_2_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_table')
    op.drop_table('fighter_table')
    op.drop_table('event_table')
    # ### end Alembic commands ###
