"""empty message

Revision ID: 4c1b35b78fe7
Revises: 0048aee1d847
Create Date: 2024-03-19 16:00:10.802008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1b35b78fe7'
down_revision = '0048aee1d847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_table')),
    sa.UniqueConstraint('name', name=op.f('uq_user_table_name'))
    )
    op.create_table('comment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user_table.id'], name=op.f('fk_comment_table_reviewer_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
