"""empty message

Revision ID: ab27815804a1
Revises: 274120851d9a
Create Date: 2024-03-20 04:29:44.992154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab27815804a1'
down_revision = '274120851d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_match_table_fighter_2_id_fighter_table', 'match_table', type_='foreignkey')
    op.drop_constraint('fk_match_table_fighter_1_id_fighter_table', 'match_table', type_='foreignkey')
    op.drop_column('match_table', 'fighter_2_id')
    op.drop_column('match_table', 'fighter_1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_table', sa.Column('fighter_1_id', sa.INTEGER(), nullable=True))
    op.add_column('match_table', sa.Column('fighter_2_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_match_table_fighter_1_id_fighter_table', 'match_table', 'fighter_table', ['fighter_1_id'], ['id'])
    op.create_foreign_key('fk_match_table_fighter_2_id_fighter_table', 'match_table', 'fighter_table', ['fighter_2_id'], ['id'])
    # ### end Alembic commands ###
